services:
  sola:
    image: reservation-app:latest
    container_name: sola_app
    ports:
      - "127.0.0.1:8002:8002"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8002
