serverAddr = "SERVER.EXAMPLE.COM"
serverPort = 7200
auth.token = "<AUTH_TOKEN>"

[[proxies]]
name = "sola-app"
type = "http"
localIP = "192.168.1.10"  # IP loadbalancerja k3s (zamaskiran)
localPort = 80
customDomains = ["ostc-app.org"]
