serverAddr = "SERVER.EXAMPLE.COM"
serverPort = 7000
auth.token = "<AUTH_TOKEN>"

[[proxies]]
name = "sola-app"
type = "http"
localIP = "<CLUSTER_IP>"
localPort = 8002
customDomains = ["ostc-app.org"]
